### ISSUE TITLE
Using node 10.18.0 git command display warnings Permission denied

### ISSUE THREAD

**Issue by clakech** [CircleCI-Public/cimg-node#82] opened 2020-06-10 19:11 UTC
Hello,

I switch to this new cimg/node:10.18.0 and when I run the command git add test.txt I get warnings:

```
warning: unable to access '/home/circleci/.config/git/ignore': Permission denied
warning: unable to access '/home/circleci/.config/git/attributes': Permission denied
```

I have open a support ticket for this but the answer is to use "a Machine User or a Deployment Key" and I don't get why and how this could solve those warnings.

Here is the full config to reproduce warnings:
```
  sample:
    docker:
      - image: cimg/node:10.18.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: touch test.txt && git add test.txt
```

I didn't get any warnings when I use circleci/node:10.18.0

**Comment by BytesGuy** [comment] 2021-05-10 11:51
Hello 👋 Is this still an issue? I tried your sample config in a job but was unable to reproduce this problem.

Two thoughts here:

* Something has since changed in the checkout script to resolve this since this issue was opened
* Somewhere in your job the permissions are getting changed, or the command is being run as a different user

I have been unable to find any other reports of this issue so far. For the moment I will close this, but please feel free to drop a comment here if this needs to be re-opened for further investigation!

**Closed as completed by BytesGuy** 2021-05-10 11:51 UTC
