### ISSUE TITLE
Node-gyp issues python2

### ISSUE THREAD

**Issue by cedricve** [CircleCI-Public/cimg-node#136] opened 2021-03-15 11:10 UTC
I'm using node-sass for SASS styling in my React app. However the build fails due to python2 missing, is this taken into account, or should I install python myself.

**Comment by stephenhmarsh** [comment] 2021-06-19 01:13
I think this is almost a duplicate of #108. You should upgrade node-gyp to the newer versions that support Python3, and use [the cimg/python image with the -node variant tag](https://circleci.com/developer/images/image/cimg/python#image-tags).  It will include a LTS version of Node.

**Comment by felicianotech** [comment] 2021-09-30 01:50
Python needs to be managed on its own. I would suggest following what @stephenhmarsh mentioned.

**Closed by felicianotech** 2021-09-30 01:50 UTC
